all: longest gfgs

longest: longest.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o longest longest.cpp

gfgs: geeks_for_geeks_solution.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o gfgs geeks_for_geeks_solution.cpp

clean:
	rm longest gfgs

