all: loop_room test_creator

loop_room: loop_room.cpp
	g++ -Wall -o loop_room loop_room.cpp

test_creator: test_creator.cpp
	g++ -Wall -o test_creator test_creator.cpp

clean: 
	rm loop_room test_creator
